import React  from "react"
import {FaHeart} from 'react-icons/fa'
const List = [
    {
        id: 1,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: './img1.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
    {
        id: 2,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: '/img2.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
    {
        id: 3,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: './img3.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
    {
        id: 4,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: './img4.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
    {
        id: 5,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: './img5.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
    {
        id: 6,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: './img6.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
    {
        id: 7,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: './img7.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
    {
        id: 8,
        name: 'Desert King',
        distance: '2345km away',
        available: 'available for 2weeks stay',
        img: './img8.png',
        price: '1MBT per night',
        icon: <FaHeart />,
    },
]

export default List
